version: '3.6'
services:

    mongo_broker:
        image : mongo
        container_name: mongo_broker


    mongo1:
        hostname: mongo1
        container_name: mongo1
        image: mongo
        ports:
            - 27017:27017
        restart: always
        entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]


    mongo2:
        hostname: mongo2
        container_name: mongo2
        image: mongo
        ports:
            - 27018:27017
        restart: always
        entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]


    mongo3:
        hostname: mongo3
        container_name: mongo3
        image: mongo
        ports:
            - 27019:27017
        restart: always
        entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
        

    server:
        image : alexburlacu/rtp-server:faf18x
        container_name: server


    cdc:
        build:
            context: cdc
        depends_on:
            - mongo1
            - mongo2
            - mongo3
            - server
        restart: always
        cap_add:
            - NET_ADMIN


    broker:
        depends_on: 
            - mongo_broker
        build:
            context: broker
        ports:
            - 8082:8082
        cap_add:
            - NET_ADMIN


    elixir:
        build: 
            context: app
        restart: always

        depends_on:
            - mongo1
            - mongo2
            - mongo3
            - server
        cap_add:
            - NET_ADMIN
