version: '3.6'
services:

    mongodb:
        image : mongo
        container_name: mongodb
        ports:
            - 27017:27017


    server:
        image : alexburlacu/rtp-server:faf18x
        container_name: server

    
    broker:
        build: 
            context: broker
        cap_add:
            - NET_ADMIN


    elixir:
        build: 
            context: app
        depends_on:
            - mongodb
            - server
        cap_add:
            - NET_ADMIN


    client:
        build: 
            context: client
        depends_on: 
            - broker
        cap_add:
            - NET_ADMIN
